In [3]:
import pandas as pd

In [4]:
# data1 = pd.read_csv("")
data2 = pd.read_csv("/Users/janghyun/Desktop/BDP/data/대여이력 정보2.csv")
data3 = pd.read_csv("/Users/janghyun/Desktop/BDP/data/대여이력 정보3.csv")

/var/folders/qy/_42009_n085fc984bjdc5v580000gn/T/ipykernel_60674/1410012723.py:2: DtypeWarning: Columns (3,5,7,9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  data2 = pd.read_csv("/Users/janghyun/Desktop/BDP/data/대여이력 정보2.csv")
/var/folders/qy/_42009_n085fc984bjdc5v580000gn/T/ipykernel_60674/1410012723.py:3: DtypeWarning: Columns (0,1,2,3,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  data3 = pd.read_csv("/Users/janghyun/Desktop/BDP/data/대여이력 정보3.csv")

In [ ]:
#data1

In [ ]:
#data1.isnull().count()

In [5]:
data2

,Unnamed: 0,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,0,SPB-13621,2018.10.1 0:02,127,현대벤처빌 앞,9,2018.10.1 0:04,124,서강대 정문 건너편,18,1,350
1,1,SPB-10560,2018.10.1 0:01,1326,상월곡역 1번출구,5,2018.10.1 0:04,1328,월곡역 3번출구,4,3,630
2,2,SPB-16256,2018.10.1 0:00,815,LIG강촌아파트 103동앞,10,2018.10.1 0:04,832,이촌1동 주민센터 뒤,11,3,44210
3,3,SPB-07969,2018.10.1 0:01,1308,안암로터리 버스정류장 앞,12,2018.10.1 0:04,614,용두동 사거리,1,3,560
4,4,SPB-10866,2018.10.1 0:02,575,중앙농협 중곡지점,9,2018.10.1 0:04,3510,중곡SK아파트앞,10,2,300
...,...,...,...,...,...,...,...,...,...,...,...,...
18246447,18246447,SPB-32717,2020.6.16 22:55,913,이마트 은평점,0,2020.6.16 23:03,931,역촌파출소,0,8,0.0
18246448,18246448,SPB-15338,2020.6.16 22:46,167,연가초등학교 옆,13,2020.6.16 23:03,175,홍연2교옆,20,17,0.0
18246449,18246449,SPB-31982,2020.6.16 22:48,559,왕십리역 4번 출구 건너편,0,2020.6.16 23:03,578,성동세무서 부근,0,16,0.0
18246450,18246450,SPB-24981,2020.6.16 22:10,1168,마곡엠밸리10단지 앞,9,2020.6.16 23:03,1168,마곡엠밸리10단지 앞,9,52,10290.0
18246451,18246451,SPB-14853,2020.6.16 22:35,2115,관악농협농산물백화점,13,2020.6.16 23:03,1822,서울 시흥동우체국 앞,3,28,0.0

In [6]:
data2.isnull().count()

Unnamed: 0    18246452
자전거번호         18246452
대여일시          18246452
대여소번호         18246452
대여대여소명        18246452
대여거치대         18246452
반납일시          18246452
반납대여소번호       18246452
반납대여소명        18246452
반납거치대         18246452
이용시간          18246452
이용거리          18246452
dtype: int64

In [7]:
data3

,자전거번호,대여일시,대여소번호,대여소명,거치대번호,반납일시,반납대여소번호,반납대여소명,반납 거치대번호,이용시간(분),이용거리(M)
0,SPB-00186,2015-09-19 0:59,115,사루비아 빌딩 앞,5.0,2015-09-19 2:39,115,사루비아 빌딩 앞,5.0,98.0,15240.0
1,SPB-00403,2015-09-19 1:22,112,극동방송국 앞,3.0,2015-09-19 6:09,102,망원역 1번출구 앞,16.0,286.0,10910.0
2,SPB-00485,2015-09-19 1:32,112,극동방송국 앞,1.0,2015-09-19 6:09,102,망원역 1번출구 앞,15.0,276.0,11000.0
3,SPB-00292,2015-09-19 7:52,221,여의도초교 앞,2.0,2015-09-19 8:56,221,여의도초교 앞,1.0,63.0,16500.0
4,SPB-00270,2015-09-19 8:56,221,여의도초교 앞,3.0,2015-09-19 9:05,210,IFC몰,2.0,8.0,1870.0
...,...,...,...,...,...,...,...,...,...,...,...
19027743,SPB-04505,2019-04-23 16:07,2175,신림동걷고싶은문화의거리입구,3.0,2019-04-23 16:14,2109,은천로입구 가로공원,7.0,7.0,970.0
19027744,SPB-16632,2019-04-23 15:48,1206,9호선종합운동장역 9번출구,18.0,2019-04-23 16:14,2332,선릉역3번출구,7.0,25.0,3180.0
19027745,SPB-18756,2019-04-23 16:07,1023,한국종합기술사옥 앞,5.0,2019-04-23 16:14,1016,해뜨는 주유소옆 리엔파크 109동앞,7.0,7.0,1330.0
19027746,SPB-16043,2019-04-23 15:38,2334,8삼호@ 2동 ( 간선도로),3.0,2019-04-23 16:14,2242,양재역 11번 출구 앞,1.0,36.0,2300.0
19027747,SPB-11765,2019-04-23 16:04,175,홍연2교옆,13.0,2019-04-23 16:14,165,중앙근린공원,3.0,9.0,2160.0

In [8]:
data3.isnull().count()

자전거번호       19027748
대여일시        19027748
대여소번호       19027748
대여소명        19027748
거치대번호       19027748
반납일시        19027748
반납대여소번호     19027748
반납대여소명      19027748
반납 거치대번호    19027748
이용시간(분)     19027748
이용거리(M)     19027748
dtype: int64

In [9]:
#data2의 불필요한 column Unamed: 0 제거
data2.drop(['Unnamed: 0'], axis = 1, inplace = True)
data2.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-13621,2018.10.1 0:02,127,현대벤처빌 앞,9,2018.10.1 0:04,124,서강대 정문 건너편,18,1,350
1,SPB-10560,2018.10.1 0:01,1326,상월곡역 1번출구,5,2018.10.1 0:04,1328,월곡역 3번출구,4,3,630
2,SPB-16256,2018.10.1 0:00,815,LIG강촌아파트 103동앞,10,2018.10.1 0:04,832,이촌1동 주민센터 뒤,11,3,44210
3,SPB-07969,2018.10.1 0:01,1308,안암로터리 버스정류장 앞,12,2018.10.1 0:04,614,용두동 사거리,1,3,560
4,SPB-10866,2018.10.1 0:02,575,중앙농협 중곡지점,9,2018.10.1 0:04,3510,중곡SK아파트앞,10,2,300